Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ryan-buckets
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f935a2ecd3a7bd5c
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: subnet-0301e8c95c652044e  # Replace with your subnet ID
          GroupSet:
            - sg-0334349ba49c1e7d1